

## foliage
block.10001=oak_leaves spruce_leaves birch_leaves jungle_leaves acacia_leaves dark_oak_leaves mangrove_leaves cherry_leaves pale_oak_leaves azalea_leaves flowering_azalea_leaves vine

## foliage connected to ground
block.10002=oak_sapling spruce_sapling birch_sapling acacia_sapling dark_oak_sapling mangrove_propagule cherry_sapling pale_oak_sapling red_mushroom brown_mushroom short_grass short_dry_grass tall_dry_grass warped_fungus warped_roots crimson_fungus crimson_roots bush fern large_fern dead_bush dandelion poppy blue_orchid allium azure_bluet red_tulip orange_tulip white_tulip pink_tulip oxeye_daisy cornflower lily_of_the_valley torchflower torchflower_crop cactus_flower closed_eyeblossom opened_eyeblossom wither_rose firefly_bush sunflower lilac rose_bush peony pitcher_plant bid_dripleaf small_dripleaf pumpkin_stem melon_stem beetroots wheat carrots potatoes sweet_berry_bush nether_wart

## foliage connected to roof
block.10003=hanging_roots

## lower half of foliage connected to ground
block.10004=tall_grass:half=lower

## upper half of foliage connected to ground
block.10005=tall_grass:half=upper