screen = [Water] [Foliage] [Other] [Debug]
screen.Water = Waves waveHeight waveSpeed
screen.Foliage = wind windSpeed windStrength
screen.Other = *
screen.Debug = debugNormals debugShadow

sliders = waveHeight waveSpeed windSpeed windStrength