screen = [Water] [Foliage] [Debug] *
screen.Water = Waves waveHeight waveSpeed waveRenderDistance waveQuality
screen.Foliage = wind windSpeed windStrength windRenderDistance
screen.Debug = debugNormals debugShadow

sliders = waveHeight waveSpeed windSpeed windStrength waveRenderDistance windRenderDistance waveQuality