screen = [Water] [Foliage] [Materials] [Lighting] [Atmosphere] DebugMode
screen.Water = Waves waveHeight waveSpeed waveRenderDistance waveQuality
screen.Foliage = doWind windSpeed windStrength windRenderDistance
screen.Materials = UseNormalMaps UseSpecularMaps
screen.Lighting = HDR Bloom ScreenSpaceReflections
screen.Atmosphere = Fog FogDistance

sliders = waveHeight waveSpeed windSpeed windStrength waveRenderDistance windRenderDistance waveQuality FogDistance